import { IDatabaseProvider, QueryResult } from '../../src/providers/IDatabaseProvider';
import { ColumnMetadata, EntityMetadata } from '../../src/core/MetadataStorage';

export type CaptureDialect = 'postgresql' | 'mssql' | 'mariadb';

/**
 * Test provider that records every SQL statement (and its parameters) passed
 * to query() so unit tests can assert the exact SQL generated by
 * DbSet/QueryBuilder/DbContext for each dialect.
 *
 * It never talks to a real database. query() returns results from a
 * configurable queue (see nextResult) or a default result.
 *
 * Placeholder styles match the real providers exactly:
 * - postgresql: $1, $2, ...   (PostgreSQLProvider)
 * - mssql:      @p0, @p1, ... (MSSQLProvider, 1-based index -> 0-based name)
 * - mariadb:    ?             (MariaDBProvider)
 */
export class SqlCaptureProvider implements IDatabaseProvider {
    /** Every query() call, in order. */
    public calls: { sql: string; params?: any[] }[] = [];

    /** Result returned by query() when the queue is empty. */
    public defaultResult: QueryResult = { rows: [], rowCount: 1 };

    private resultQueue: QueryResult[] = [];

    constructor(private dialect: CaptureDialect) {}

    /** Queue a result to be returned by the next query() call. */
    nextResult(result: QueryResult): void {
        this.resultQueue.push(result);
    }

    /** Convenience accessor for the most recent query() call. */
    get lastCall(): { sql: string; params?: any[] } | undefined {
        return this.calls[this.calls.length - 1];
    }

    /** Clear recorded calls and queued results. */
    reset(): void {
        this.calls = [];
        this.resultQueue = [];
    }

    getDialect(): string {
        return this.dialect;
    }

    async connect(): Promise<void> {
        // no-op
    }

    async disconnect(): Promise<void> {
        // no-op
    }

    async query(text: string, params?: any[]): Promise<QueryResult> {
        this.calls.push({ sql: text, params });
        return this.resultQueue.length > 0 ? this.resultQueue.shift()! : this.defaultResult;
    }

    async beginTransaction(): Promise<void> {
        // no-op
    }

    async commitTransaction(): Promise<void> {
        // no-op
    }

    async rollbackTransaction(): Promise<void> {
        // no-op
    }

    getParameterPlaceholder(index: number): string {
        switch (this.dialect) {
            case 'postgresql':
                return `$${index}`;
            case 'mssql':
                // Convert from 1-based caller convention to 0-based MSSQL binding
                return `@p${index - 1}`;
            case 'mariadb':
                return '?';
        }
    }

    generateSelectSql(tableName: string, whereClause?: string): string {
        if (whereClause) {
            return `SELECT * FROM ${tableName} WHERE ${whereClause}`;
        }
        return `SELECT * FROM ${tableName}`;
    }

    generateInsertSql(tableName: string, columns: ColumnMetadata[]): string {
        const columnNames = columns.map(c => c.columnName).join(', ');
        const placeholders = columns.map((_, i) => this.getParameterPlaceholder(i + 1)).join(', ');
        return `INSERT INTO ${tableName} (${columnNames}) VALUES (${placeholders})`;
    }

    generateUpdateSql(tableName: string, columns: ColumnMetadata[], pkColumn: ColumnMetadata): string {
        const setClause = columns
            .map((c, i) => `${c.columnName} = ${this.getParameterPlaceholder(i + 1)}`)
            .join(', ');
        return `UPDATE ${tableName} SET ${setClause} WHERE ${pkColumn.columnName} = ${this.getParameterPlaceholder(columns.length + 1)}`;
    }

    generateDeleteSql(tableName: string, pkColumn: ColumnMetadata): string {
        return `DELETE FROM ${tableName} WHERE ${pkColumn.columnName} = ${this.getParameterPlaceholder(1)}`;
    }

    mapType(tsType: string): string {
        return tsType;
    }

    normalizeType(dbType: string): string {
        return dbType.toLowerCase();
    }

    getAutoIncrementType(): string {
        return 'INTEGER';
    }

    isTypeMismatch(_entityType: string, _dbType: string): boolean {
        return false;
    }

    getSchemaColumnsQuery(tableName: string): { sql: string; params: any[] } {
        return {
            sql: `SELECT column_name, data_type FROM information_schema.columns WHERE table_name = ${this.getParameterPlaceholder(1)}`,
            params: [tableName],
        };
    }

    // DDL generation is not exercised by these SQL-generation unit tests.
    generateCreateTableSql(_entity: EntityMetadata): string {
        throw new Error('SqlCaptureProvider: generateCreateTableSql not implemented');
    }

    generateAddColumnSql(_tableName: string, _column: ColumnMetadata): string {
        throw new Error('SqlCaptureProvider: generateAddColumnSql not implemented');
    }

    generateAlterColumnTypeSql(_tableName: string, _column: ColumnMetadata): string {
        throw new Error('SqlCaptureProvider: generateAlterColumnTypeSql not implemented');
    }

    generateAddForeignKeySql(): string {
        throw new Error('SqlCaptureProvider: generateAddForeignKeySql not implemented');
    }

    generateCreateIndexSql(): string {
        throw new Error('SqlCaptureProvider: generateCreateIndexSql not implemented');
    }

    generateCreateUniqueConstraintSql(): string {
        throw new Error('SqlCaptureProvider: generateCreateUniqueConstraintSql not implemented');
    }

    generateCreateJoinTableSql(): string {
        throw new Error('SqlCaptureProvider: generateCreateJoinTableSql not implemented');
    }
}
